### ISSUE TITLE
Do not create branches

### ISSUE THREAD

**Issue by nelmiux** [iOS-Mobile-Dev/todo#3]
Creating branches to implement code when working in teams is just not the way to go, at the en all code has to be integrated, so is just one dev branch.

If you want to work without marge conflicts with a branch you need to fork dev on your account, make changes and ask for pull request.

Maybe reading git documentation and best practices on git will help.

This need to be fixed, and just have one dev branch.

There is not a basic understanding of how git works.

**Comment by killvung** [comment]
I kinda understand the idea, but seriously had never tried it before. 
Is it what Git / Github suggest to do?

**Comment by killvung** [comment]
Hey I tried to fork a repo, modify something, and attempt to create pull request, but it is impossible to do so, because I was trying to compare to the same branch they said.

**Comment by nelmiux** [comment]
you need to create your a local branch, when you fork you are over the same branch, in your part you create a branch in order to do pull request. I will show how this is Friday
