### ISSUE TITLE
Do we need this string here in settings? Please leave blank or as "password"

### ISSUE THREAD

**Issue by quyenc** [iOS-Mobile-Dev/todo#69]
"Do you think the password is really shown"
![2](https://cloud.githubusercontent.com/assets/8742860/14931852/8df1ed54-0e34-11e6-8623-44a6257900f5.jpg)
"

**Comment by killvung** [comment]
It would be funny if do

---

Regard
Kiu Fung Lam

**Comment by killvung** [comment]
But you can take it off if preferred

---

Regard
Kiu Fung Lam

**Comment by nelmiux** [comment]
I will take this out, this is not the kind of "funny" we want on this app
