### ISSUE TITLE
Registration Screen Fields don't fit the screen

### ISSUE THREAD

**Issue by nelmiux** [iOS-Mobile-Dev/todo#7]

**Comment by killvung** [comment]
Hey Nelma, I was trying to see how does the registration screen field not fit the screen, but it seems that the screen has no problem at all, therefore can you tell us how does it not fit the screen in detail? 

Thank oyu

![simulator screen shot mar 9 2016 4 05 43 pm](https://cloud.githubusercontent.com/assets/7685886/13652263/d3f2eb56-e610-11e5-86c6-f99f9fe8a2d8.png)

**Comment by nelmiux** [comment]
This is just not the registration screen
